#!/bin/bash

if test ! -e /tmp/weather-url
then
		sleep 7
fi

condition=$(awk -F\' '/acm_RecentLocationsCarousel\.push/{print ""$13"" }' /tmp/weather-url | awk -F\" '{print $2}' | head -1) 

condition=$(echo $condition | awk '{print tolower($0)}')
condition+=';'

cond=$(grep "^$condition" /home/daniel/scripts/files/weather-list | awk -F\; '{print $2}')

echo -e $cond
